file-scanner:
  root-path: ./test-data
  include-extensions: [".txt", ".pdf", ".md"]

vectorstore:
  base-url: http://localhost:8080
  api-key: secret

ollama:
  base-url: http://localhost:11434

embedding:
  model: bge-m3
  dimension: 1024

rag:
  chunk-size: 1200
  chunk-overlap: 200